import { createContext } from 'react';

export const jobPostContext = createContext({
  jobPosts: [],
  setJobPosts: () => { },
});

// id, company, title, region, time, pay, category, condition, preference, content, author, createdAt
export const initialJobPosts = [
  {
    id: 1,
    company: '세븐일레븐 고척점',
    title: '세븐일레븐 평일 17~23시 알바 구함 (주휴수당 지급)',
    region: '고척동',
    time: '17:00~23:00',
    pay: '10500원',
    category: '편의점',
    condition: '평일',
    preference: '주휴수당',
    content: '주휴수당 포함, 물품 정리 및 계산대 업무',
    author: '관리자',
    createdAt: new Date('2025-10-03T10:00:00').toISOString(),
  },
  {
    id: 2,
    company: '한솥도시락 강남점',
    title: '한솥도시락 조리 및 포장 보조 알바 (주중)',
    region: '강남역',
    time: '10:00~14:00',
    pay: '10000원',
    category: '음식점',
    condition: '평일',
    preference: '조리 경험자 우대',
    content: '도시락 조리 보조, 포장, 배달 준비 업무',
    author: '매니저',
    createdAt: new Date('2025-10-04T09:30:00').toISOString(),
  },
  {
    id: 3,
    company: '바르다김선생 홍대점',
    title: '바르다김선생 주말 주방 어시스턴트 모집',
    region: '홍대입구',
    time: '11:00~16:00',
    pay: '10800원',
    category: '음식점',
    condition: '주말',
    preference: '문서작성 가능자 우대',
    content: '김밥 및 반찬 포장 보조, 매장 정리',
    author: '점장',
    createdAt: new Date('2025-10-05T11:00:00').toISOString(),
  },
  {
    id: 4,
    company: 'ABC 법률사무소',
    title: '사무 보조 알바 모집 (계약서 검토 및 서류 정리)',
    region: '역삼동',
    time: '09:00~18:00',
    pay: '12000원',
    category: '사무직',
    condition: '주중',
    preference: '문서작성 능숙자 우대',
    content: '계약서 스캔, 서류 정리, 간단한 자료 입력 업무',
    author: '인사담당',
    createdAt: new Date('2025-10-06T08:45:00').toISOString(),
  },
  {
    id: 5,
    company: '스타벅스 삼성점',
    title: '스타벅스 바리스타 알바 (평일 오후)',
    region: '삼성역',
    time: '14:00~20:00',
    pay: '11500원',
    category: '카페',
    condition: '평일',
    preference: '친절 서비스 가능자',
    content: '음료 제조, 고객응대, 매장 청소',
    author: '점장',
    createdAt: new Date('2025-10-07T14:00:00').toISOString(),
  },
  {
    id: 6,
    company: '쿠팡 물류센터',
    title: '물류센터 피킹·패킹 보조 알바 (주말)',
    region: '부천시',
    time: '08:00~17:00',
    pay: '10200원',
    category: '물류',
    condition: '주말',
    preference: '체력 좋은 분 우대',
    content: '상품 피킹, 패킹, 발송 준비 업무',
    author: '현장매니저',
    createdAt: new Date('2025-10-08T07:50:00').toISOString(),
  },
];
